[project]
name = "krpc-module"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "krpc==0.5.3",
    "poliastro>=0.17.0",
]
